apiVersion: v1
kind: Service
metadata:
  name: bff-external-service
spec:
  selector:
    app: bff
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30000
